# Generated by Django 5.2.4 on 2025-07-30 19:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 30, 19, 1, 18, 870277, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
