# Generated by Django 5.2.4 on 2025-07-31 06:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_alter_postmodel_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 31, 6, 30, 35, 95551, tzinfo=datetime.timezone.utc)),
        ),
    ]
